repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Update this to the version you want to use
    hooks:
      - id: trailing-whitespace
      # Add other hooks from pre-commit-hooks here as needed
  - repo: https://github.com/psf/black
    rev: 24.1.1  # Update this to the version of Black you want to use
    hooks:
      - id: black
        language_version: python3
